exclution_groups = [1, 3, 3, 1, 1, 1, 1, 4, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1, 2, 1, 1, 2, 2, 1, 4, 1, 2, 1, 3, 1, 1]

exclution_attris = [
        'gender',
        'race',
        'age',
        'wrinkle',
        'makeup',
        'bald',
        'largeForehead',
        'face',
        'narrowEye',
        'sleepEye',
        'slantEye',
        'sharpEye',
        'flabbyEye',
        'sizeOfEye',
        'underEyePuffiness',
        'sizeOfNose',
        'highFlatNose',
        'hookNose',
        'wideNarrowNose',
        'toothy',
        'smile',
        'sizeOfMouth',
        'thickThinLips',
        'doubleChin',
        'eyebrowShape',
        'bushyEyebrows',
        'thickThinEyebrows',
        'mustache',
        'beardShape',
        'whiskers',
        'highCheekbone'
    ]

separate_attributes = ['Women',
                       'Asian',  # Asian and Indian
                       'White',
                       'Black',
                       'Youth',  # teenager and youth
                       'Middle',
                       'Old',
                       'Wrinkle',
                       'MakeUp',
                       'Bald',
                       'LargeForehead',
                       'RoundFace',
                       'DiamondFace',
                       'OvalFace',
                       'SquareShapeFace',  # SquareFace and RectangularFace
                       'NarrowEye',
                       'SleepyEye',
                       'SlantEye',
                       'SharpEye',
                       'FlabbyEye',
                       'BigEye',
                       'SmallEye',
                       'UnderEyePuffiness',
                       'BigNose',
                       'SmallNose',
                       'HighNose',
                       'FlatNose',
                       'HookNose',
                       'WideNose',
                       'NarrowNose',
                       'Toothy',
                       'Smile',
                       'BigMouth',
                       'SmallMouth',
                       'ThickLips',
                       'ThinLips',
                       'DoubleChin',
                       'ArchedEyebrows',
                       'FlatEyebrow',
                       'SlantedEyebrows',
                       'UpsideDownSlantedEyebrows',
                       'BushyEyebrows',
                       'ThickEyebrows',
                       'ThinEyebrows',
                       'Mustache',
                       'Goatee',
                       'Whiskers',
                       'OtherBeard&NoBeard',
                       'HighCheekbones',
                       'SquareJaw']
